name: Workflow Conclusion Slack Notifier

on:
  workflow_call:
    inputs:
      workflow_name:
        description: 'The name of the workflow'
        required: false
        type: string
        default: ''
      display_title:
        description: 'The display title of the workflow run'
        required: false
        type: string
        default: ''
      conclusion:
        description: 'The result of the workflow run'
        required: false
        type: string
        default: ''
      html_url:
        description: 'The HTML URL of the workflow run'
        required: false
        type: string
        default: ''
      repo_full_name:
        description: 'The full name of the repository'
        required: false
        type: string
        default: ''
    secrets:
      slack_webhook_url:
        description: 'The Slack webhook URL'
        required: true

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Set Payload Parameters
        id: payload-params
        run: |
          echo "workflow=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
          echo "title=${{ format('{0}: {1}', github.event.workflow_run.event, github.event.workflow_run.display_title) }}" >> $GITHUB_OUTPUT
          echo "result=${{ github.event.workflow_run.conclusion }}" >> $GITHUB_OUTPUT
          echo "url=${{ github.event.workflow_run.html_url }}" >> $GITHUB_OUTPUT
          echo "repo=${{ github.event.repository.full_name }}" >> $GITHUB_OUTPUT

      - name: Send workflow conclusion payload to Slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
        with:
          payload: |
            {
              "workflow": "${{ steps.payload-params.outputs.workflow }}",
              "title": "${{ steps.payload-params.outputs.title }}",
              "result": "${{ steps.payload-params.outputs.result == 'success' && '🟢' || '🔴' }} ${{ steps.payload-params.outputs.result }}",
              "url": "${{ steps.payload-params.outputs.url }}",
              "repo": "${{ steps.payload-params.outputs.repo }}"
            }
